# Generated by Django 5.2.4 on 2025-09-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='college',
            field=models.CharField(choices=[('arts_science', 'College of Arts & Science'), ('business_finance', 'College of Business & Finance'), ('engineering', 'College of Engineering'), ('it', 'College of Information Technology'), ('medical_health', 'College of Medical & Health Sciences'), ('admin', 'Administration')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='custom_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
