# Generated by Django 5.2.4 on 2025-08-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidtag',
            name='custom_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
