# Generated by Django 5.2.4 on 2025-09-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='attendance_warning_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='failed_due_to_attendance',
            field=models.BooleanField(default=False),
        ),
    ]
